FROM basilerichard95/raspberrypi2_jupyter_lab:base

# Updating and installing libraries for matplotlib
RUN apt-get update && apt-get install libatlas-base-dev libopenjp2-7 libtiff5 libgl1-mesa-glx libjpeg62

RUN pip3 --no-cache-dir install pandas && \
    pip3 --no-cache-dir install matplotlib
